# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'nsim.ui'
#
# Created: Tue Apr 24 18:31:21 2018
#      by: pyside2-uic  running on PySide2 5.9.0a1.dev1524086444
#
# WARNING! All changes made in this file will be lost!

from PySide2 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(818, 824)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.splitter = QtWidgets.QSplitter(self.centralwidget)
        self.splitter.setOrientation(QtCore.Qt.Horizontal)
        self.splitter.setObjectName("splitter")
        self.dirView = QtWidgets.QGroupBox(self.splitter)
        self.dirView.setAutoFillBackground(False)
        self.dirView.setFlat(False)
        self.dirView.setObjectName("dirView")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.dirView)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.dirTreeView = QtWidgets.QTreeView(self.dirView)
        self.dirTreeView.setObjectName("dirTreeView")
        self.horizontalLayout_2.addWidget(self.dirTreeView)
        self.layoutWidget = QtWidgets.QWidget(self.splitter)
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.generalGroupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.generalGroupBox.setObjectName("generalGroupBox")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.generalGroupBox)
        self.horizontalLayout.setObjectName("horizontalLayout")
        spacerItem = QtWidgets.QSpacerItem(39, 33, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem)
        self.openDirButton = QtWidgets.QPushButton(self.generalGroupBox)
        self.openDirButton.setObjectName("openDirButton")
        self.horizontalLayout.addWidget(self.openDirButton)
        self.runPennSimButton = QtWidgets.QPushButton(self.generalGroupBox)
        self.runPennSimButton.setEnabled(False)
        self.runPennSimButton.setAutoDefault(False)
        self.runPennSimButton.setDefault(False)
        self.runPennSimButton.setFlat(False)
        self.runPennSimButton.setObjectName("runPennSimButton")
        self.horizontalLayout.addWidget(self.runPennSimButton)
        spacerItem1 = QtWidgets.QSpacerItem(39, 30, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addWidget(self.generalGroupBox)
        self.scriptGroupBox = QtWidgets.QGroupBox(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.scriptGroupBox.sizePolicy().hasHeightForWidth())
        self.scriptGroupBox.setSizePolicy(sizePolicy)
        self.scriptGroupBox.setObjectName("scriptGroupBox")
        self.gridLayout = QtWidgets.QGridLayout(self.scriptGroupBox)
        self.gridLayout.setObjectName("gridLayout")
        self.runButton = QtWidgets.QPushButton(self.scriptGroupBox)
        self.runButton.setEnabled(False)
        self.runButton.setObjectName("runButton")
        self.gridLayout.addWidget(self.runButton, 6, 0, 1, 4)
        self.loadScriptButton = QtWidgets.QPushButton(self.scriptGroupBox)
        self.loadScriptButton.setObjectName("loadScriptButton")
        self.gridLayout.addWidget(self.loadScriptButton, 5, 0, 1, 2)
        self.scriptComboBox = QtWidgets.QComboBox(self.scriptGroupBox)
        self.scriptComboBox.setEnabled(True)
        self.scriptComboBox.setToolTip("")
        self.scriptComboBox.setObjectName("scriptComboBox")
        self.scriptComboBox.addItem("")
        self.scriptComboBox.addItem("")
        self.gridLayout.addWidget(self.scriptComboBox, 3, 2, 1, 2)
        self.programNameEditLabel = QtWidgets.QLabel(self.scriptGroupBox)
        self.programNameEditLabel.setObjectName("programNameEditLabel")
        self.gridLayout.addWidget(self.programNameEditLabel, 1, 0, 1, 2)
        self.selectTestLabel = QtWidgets.QLabel(self.scriptGroupBox)
        self.selectTestLabel.setEnabled(True)
        self.selectTestLabel.setObjectName("selectTestLabel")
        self.gridLayout.addWidget(self.selectTestLabel, 3, 0, 1, 2)
        self.programNameEdit = QtWidgets.QLineEdit(self.scriptGroupBox)
        self.programNameEdit.setObjectName("programNameEdit")
        self.gridLayout.addWidget(self.programNameEdit, 1, 2, 1, 2)
        self.scriptEdit = QtWidgets.QPlainTextEdit(self.scriptGroupBox)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(1)
        sizePolicy.setHeightForWidth(self.scriptEdit.sizePolicy().hasHeightForWidth())
        self.scriptEdit.setSizePolicy(sizePolicy)
        self.scriptEdit.setObjectName("scriptEdit")
        self.gridLayout.addWidget(self.scriptEdit, 4, 0, 1, 4)
        self.osLabel = QtWidgets.QLabel(self.scriptGroupBox)
        self.osLabel.setObjectName("osLabel")
        self.gridLayout.addWidget(self.osLabel, 2, 0, 1, 2)
        self.osComboBox = QtWidgets.QComboBox(self.scriptGroupBox)
        self.osComboBox.setObjectName("osComboBox")
        self.osComboBox.addItem("")
        self.osComboBox.addItem("")
        self.osComboBox.addItem("")
        self.osComboBox.addItem("")
        self.gridLayout.addWidget(self.osComboBox, 2, 2, 1, 2)
        self.saveAsScriptButton = QtWidgets.QPushButton(self.scriptGroupBox)
        self.saveAsScriptButton.setEnabled(False)
        self.saveAsScriptButton.setObjectName("saveAsScriptButton")
        self.gridLayout.addWidget(self.saveAsScriptButton, 5, 2, 1, 2)
        self.allTestsCheckBox = QtWidgets.QCheckBox(self.scriptGroupBox)
        self.allTestsCheckBox.setEnabled(False)
        self.allTestsCheckBox.setObjectName("allTestsCheckBox")
        self.gridLayout.addWidget(self.allTestsCheckBox, 9, 2, 1, 1)
        self.cliModeCheckBox = QtWidgets.QCheckBox(self.scriptGroupBox)
        self.cliModeCheckBox.setEnabled(False)
        self.cliModeCheckBox.setObjectName("cliModeCheckBox")
        self.gridLayout.addWidget(self.cliModeCheckBox, 9, 1, 1, 1)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem2, 9, 0, 1, 1)
        spacerItem3 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.MinimumExpanding, QtWidgets.QSizePolicy.Minimum)
        self.gridLayout.addItem(spacerItem3, 9, 3, 1, 1)
        self.verticalLayout.addWidget(self.scriptGroupBox)
        self.pennSimGroupBox = QtWidgets.QGroupBox(self.layoutWidget)
        self.pennSimGroupBox.setCheckable(True)
        self.pennSimGroupBox.setObjectName("pennSimGroupBox")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.pennSimGroupBox)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.pennSimTextBrowser = QtWidgets.QTextBrowser(self.pennSimGroupBox)
        self.pennSimTextBrowser.setObjectName("pennSimTextBrowser")
        self.verticalLayout_2.addWidget(self.pennSimTextBrowser)
        self.clearCLIOutputButton = QtWidgets.QPushButton(self.pennSimGroupBox)
        self.clearCLIOutputButton.setObjectName("clearCLIOutputButton")
        self.verticalLayout_2.addWidget(self.clearCLIOutputButton)
        self.workingDirLabel = QtWidgets.QLabel(self.pennSimGroupBox)
        self.workingDirLabel.setEnabled(True)
        font = QtGui.QFont()
        font.setItalic(False)
        self.workingDirLabel.setFont(font)
        self.workingDirLabel.setToolTip("")
        self.workingDirLabel.setText("")
        self.workingDirLabel.setTextInteractionFlags(QtCore.Qt.LinksAccessibleByMouse|QtCore.Qt.TextSelectableByMouse)
        self.workingDirLabel.setObjectName("workingDirLabel")
        self.verticalLayout_2.addWidget(self.workingDirLabel)
        self.verticalLayout.addWidget(self.pennSimGroupBox)
        self.horizontalLayout_3.addWidget(self.splitter)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setEnabled(True)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 818, 28))
        self.menubar.setObjectName("menubar")
        self.menuFile = QtWidgets.QMenu(self.menubar)
        self.menuFile.setObjectName("menuFile")
        self.menuHelp = QtWidgets.QMenu(self.menubar)
        self.menuHelp.setObjectName("menuHelp")
        self.menuView = QtWidgets.QMenu(self.menubar)
        self.menuView.setObjectName("menuView")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.actionOpen_Dir = QtWidgets.QAction(MainWindow)
        self.actionOpen_Dir.setObjectName("actionOpen_Dir")
        self.actionShow_PennSimCLIOutput = QtWidgets.QAction(MainWindow)
        self.actionShow_PennSimCLIOutput.setCheckable(True)
        self.actionShow_PennSimCLIOutput.setObjectName("actionShow_PennSimCLIOutput")
        self.menuFile.addAction(self.actionOpen_Dir)
        self.menuView.addAction(self.actionShow_PennSimCLIOutput)
        self.menubar.addAction(self.menuFile.menuAction())
        self.menubar.addAction(self.menuView.menuAction())
        self.menubar.addAction(self.menuHelp.menuAction())
        self.programNameEditLabel.setBuddy(self.programNameEdit)
        self.selectTestLabel.setBuddy(self.scriptComboBox)
        self.osLabel.setBuddy(self.osComboBox)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(QtWidgets.QApplication.translate("MainWindow", "NSim", None, -1))
        self.dirView.setTitle(QtWidgets.QApplication.translate("MainWindow", "No Root Folder Selected", None, -1))
        self.generalGroupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "General", None, -1))
        self.openDirButton.setText(QtWidgets.QApplication.translate("MainWindow", "Open Folder", None, -1))
        self.runPennSimButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Starts new PennSim Instance", None, -1))
        self.runPennSimButton.setText(QtWidgets.QApplication.translate("MainWindow", "Run PennSim", None, -1))
        self.scriptGroupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "Script", None, -1))
        self.runButton.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Run script loaded in script editor", None, -1))
        self.runButton.setText(QtWidgets.QApplication.translate("MainWindow", "Run Script", None, -1))
        self.loadScriptButton.setText(QtWidgets.QApplication.translate("MainWindow", "Load Script", None, -1))
        self.scriptComboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "Default", None, -1))
        self.scriptComboBox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "Assembly Test", None, -1))
        self.programNameEditLabel.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Provide name to find automatically or select from root folder tree.", None, -1))
        self.programNameEditLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Program Name:", None, -1))
        self.selectTestLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Built-in Script:", None, -1))
        self.programNameEdit.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Defines name for autofilling built-in scripts and for \'All Programs\' run option.", None, -1))
        self.programNameEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "Name of program to test", None, -1))
        self.scriptEdit.setPlaceholderText(QtWidgets.QApplication.translate("MainWindow", "PennSim script viewing / editing area", None, -1))
        self.osLabel.setText(QtWidgets.QApplication.translate("MainWindow", "Operating System:", None, -1))
        self.osComboBox.setItemText(0, QtWidgets.QApplication.translate("MainWindow", "lc3os", None, -1))
        self.osComboBox.setItemText(1, QtWidgets.QApplication.translate("MainWindow", "p2os", None, -1))
        self.osComboBox.setItemText(2, QtWidgets.QApplication.translate("MainWindow", "p3os", None, -1))
        self.osComboBox.setItemText(3, QtWidgets.QApplication.translate("MainWindow", "Other...", None, -1))
        self.saveAsScriptButton.setText(QtWidgets.QApplication.translate("MainWindow", "Save Script As", None, -1))
        self.allTestsCheckBox.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Recursively runs script against all <Program Name>\'s found with selected root or current folder. Program Name determines the program name searched for, not anything in the script.", None, -1))
        self.allTestsCheckBox.setStatusTip(QtWidgets.QApplication.translate("MainWindow", "Recursively runs script against all <Program Name>\'s found with selected root folder.", None, -1))
        self.allTestsCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "All programs", None, -1))
        self.cliModeCheckBox.setToolTip(QtWidgets.QApplication.translate("MainWindow", "Run PennSim in command-line mode.", None, -1))
        self.cliModeCheckBox.setText(QtWidgets.QApplication.translate("MainWindow", "CLI Mode", None, -1))
        self.pennSimGroupBox.setTitle(QtWidgets.QApplication.translate("MainWindow", "PennSim CLI Output", None, -1))
        self.clearCLIOutputButton.setText(QtWidgets.QApplication.translate("MainWindow", "Clear Output", None, -1))
        self.menuFile.setTitle(QtWidgets.QApplication.translate("MainWindow", "File", None, -1))
        self.menuHelp.setTitle(QtWidgets.QApplication.translate("MainWindow", "Help", None, -1))
        self.menuView.setTitle(QtWidgets.QApplication.translate("MainWindow", "View", None, -1))
        self.actionOpen_Dir.setText(QtWidgets.QApplication.translate("MainWindow", "Open Folder", None, -1))
        self.actionShow_PennSimCLIOutput.setText(QtWidgets.QApplication.translate("MainWindow", "Show PennSim CLI Output", None, -1))

